"""Repository inventory: which files exist, what they are, and what is excluded.

The inventory is the base layer of repository forensics. It walks the
workspace once, prunes excluded directories (vendor trees, build output,
caches, provider runtime state; configurable via `lord.toml`), and classifies
every remaining file by kind and language. Classification is by path, name
and a small content probe; it is deliberately simple and explainable.
"""

from __future__ import annotations

import fnmatch
import os
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from lord.config import LordConfig
from lord.paths import to_rel_posix

KINDS = ("source", "test", "config", "manifest", "script", "docs", "generated", "data", "other")

LANGUAGE_BY_EXT: dict[str, str] = {
    ".py": "python", ".pyi": "python",
    ".js": "javascript", ".mjs": "javascript", ".cjs": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "typescript", ".mts": "typescript", ".cts": "typescript",
    ".java": "java", ".kt": "kotlin", ".kts": "kotlin", ".go": "go", ".rs": "rust", ".rb": "ruby",
    ".php": "php", ".cs": "csharp", ".c": "c", ".h": "c", ".cpp": "cpp", ".cc": "cpp", ".hpp": "cpp",
    ".swift": "swift", ".dart": "dart", ".scala": "scala", ".sql": "sql", ".html": "html",
    ".css": "css", ".scss": "scss", ".vue": "vue", ".svelte": "svelte",
    ".sh": "shell", ".bash": "shell", ".ps1": "powershell", ".bat": "batch", ".cmd": "batch",
    ".json": "json", ".yaml": "yaml", ".yml": "yaml", ".toml": "toml", ".ini": "ini", ".cfg": "ini",
    ".xml": "xml", ".env": "dotenv", ".md": "markdown", ".rst": "rst", ".txt": "text",
    ".csv": "csv", ".tsv": "csv",
}
LANGUAGE_BY_NAME: dict[str, str] = {"dockerfile": "dockerfile", "makefile": "makefile", "cmakelists.txt": "cmake"}

SOURCE_LANGUAGES = {
    "python", "javascript", "typescript", "java", "kotlin", "go", "rust", "ruby", "php", "csharp",
    "c", "cpp", "swift", "dart", "scala", "sql", "html", "css", "scss", "vue", "svelte",
}
CONFIG_LANGUAGES = {"json", "yaml", "toml", "ini", "xml", "dotenv"}
DOC_LANGUAGES = {"markdown", "rst", "text"}
SCRIPT_LANGUAGES = {"shell", "powershell", "batch", "dockerfile", "makefile", "cmake"}
DATA_LANGUAGES = {"csv"}

MANIFEST_NAMES = {
    "package.json", "pyproject.toml", "setup.py", "setup.cfg", "requirements.txt", "pipfile",
    "cargo.toml", "go.mod", "pom.xml", "build.gradle", "build.gradle.kts", "gemfile",
    "composer.json", "cmakelists.txt", "makefile", "dockerfile", "pubspec.yaml",
}
MANIFEST_SUFFIXES = (".csproj", ".sln", ".gemspec")

TEST_DIR_NAMES = {"test", "tests", "__tests__", "spec", "specs", "testing", "e2e"}
TEST_FILE_PATTERNS = (
    "test_*.py", "*_test.py", "conftest.py", "*.test.*", "*.spec.*", "*Test.java", "*Tests.java",
    "*Test.kt", "*Tests.cs", "*_test.go", "*_spec.rb", "*_test.rs",
)
SCRIPT_DIR_NAMES = {"scripts", "script", "bin", "tools"}
GENERATED_DIR_NAMES = {"generated", "__generated__", "codegen", "gen"}
GENERATED_SUFFIXES = (".pb.go", ".pb.py", "_pb2.py", "_pb2_grpc.py", ".g.dart", ".generated.ts", ".generated.js")
GENERATED_MARKERS = (b"@generated", b"DO NOT EDIT", b"Code generated by", b"autogenerated", b"auto-generated", b"AUTO-GENERATED")

PROBE_BYTES = 4096
HEADER_LINES = 5          # generated-code markers are only honoured in the file header
MAX_LINECOUNT_BYTES = 2_000_000


@dataclass
class FileRecord:
    path: str                 # workspace-relative POSIX path
    kind: str
    language: str             # "" when unknown
    size: int
    is_text: bool
    lines: int | None = None
    reason: str = ""          # why it was classified generated/test/etc. (short)

    @property
    def analyzable(self) -> bool:
        return self.is_text and self.kind in ("source", "test", "script") and self.language != ""


@dataclass
class Inventory:
    root: str
    files: list[FileRecord] = field(default_factory=list)
    excluded_dirs: list[str] = field(default_factory=list)
    project_roots: list[str] = field(default_factory=list)   # dirs containing a manifest

    def by_kind(self) -> Counter:
        return Counter(f.kind for f in self.files)

    def by_language(self) -> Counter:
        return Counter(f.language or "unknown" for f in self.files if f.kind in ("source", "test", "script"))

    def get(self, path: str) -> FileRecord | None:
        return next((f for f in self.files if f.path == path), None)

    def project_root_of(self, path: str) -> str:
        """Deepest project root (a directory holding a manifest) containing `path`; "." otherwise.

        A monorepo's sub-projects legitimately reuse names; analyses that
        compare symbols by name stay inside one project root.
        """
        best = "."
        for root in self.project_roots:
            if root != "." and (path == root or path.startswith(root.rstrip("/") + "/")) and len(root) > len(best):
                best = root
        return best

    def to_dict(self) -> dict[str, Any]:
        return {
            "root": self.root,
            "files": [asdict(f) for f in self.files],
            "excluded_dirs": self.excluded_dirs,
            "project_roots": self.project_roots,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Inventory":
        return cls(
            root=data["root"],
            files=[FileRecord(**f) for f in data.get("files", [])],
            excluded_dirs=list(data.get("excluded_dirs", [])),
            project_roots=list(data.get("project_roots", [])),
        )


def language_of(path: Path) -> str:
    lower = path.name.lower()
    if lower in LANGUAGE_BY_NAME:
        return LANGUAGE_BY_NAME[lower]
    return LANGUAGE_BY_EXT.get(path.suffix.lower(), "")


def _is_excluded_file(rel: str, name: str, config: LordConfig) -> bool:
    return any(fnmatch.fnmatch(name, g) or fnmatch.fnmatch(rel, g) for g in config.exclude_globs)


def _is_excluded_dir(rel: str, name: str, config: LordConfig) -> bool:
    if name in config.exclude_dirs:
        return True
    return any(fnmatch.fnmatch(rel, g.rstrip("/")) for g in config.exclude_globs if g.endswith("/"))


def classify(rel: str, language: str, probe: bytes, is_text: bool) -> tuple[str, str]:
    """Return (kind, reason) for a file. Order matters: manifests and generated
    code are recognised before source so they never masquerade as code."""
    parts = rel.split("/")
    name = parts[-1]
    lower = name.lower()
    dirs = {p.lower() for p in parts[:-1]}

    if lower in MANIFEST_NAMES or lower.endswith(MANIFEST_SUFFIXES) or fnmatch.fnmatch(lower, "requirements*.txt"):
        return "manifest", "manifest filename"
    if dirs & GENERATED_DIR_NAMES:
        return "generated", "generated directory"
    if lower.endswith(GENERATED_SUFFIXES):
        return "generated", "generated suffix"
    if is_text:
        header = b"\n".join(probe.splitlines()[:HEADER_LINES])
        if any(marker in header for marker in GENERATED_MARKERS):
            return "generated", "generated marker in header"
    if language in SOURCE_LANGUAGES or language == "":
        if dirs & TEST_DIR_NAMES and (language in SOURCE_LANGUAGES):
            return "test", "test directory"
        if any(fnmatch.fnmatch(name, p) for p in TEST_FILE_PATTERNS) and language in SOURCE_LANGUAGES:
            return "test", "test filename"
    if language in SCRIPT_LANGUAGES:
        return "script", "script language"
    if language in SOURCE_LANGUAGES:
        if dirs & SCRIPT_DIR_NAMES:
            return "script", "script directory"
        return "source", ""
    if language in CONFIG_LANGUAGES:
        return "config", ""
    if language in DOC_LANGUAGES:
        return "docs", ""
    if language in DATA_LANGUAGES:
        return "data", ""
    return "other", ""


def build_inventory(config: LordConfig) -> Inventory:
    root = config.root.resolve()
    inventory = Inventory(root=str(root))
    project_roots: set[str] = set()

    for current, dirnames, filenames in os.walk(root, topdown=True):
        current_path = Path(current)
        rel_dir = "" if current_path == root else to_rel_posix(current_path, root)

        kept: list[str] = []
        for d in sorted(dirnames):
            rel = f"{rel_dir}/{d}" if rel_dir else d
            if (current_path / d).is_symlink() or _is_excluded_dir(rel, d, config):
                inventory.excluded_dirs.append(rel)
            else:
                kept.append(d)
        dirnames[:] = kept

        for filename in sorted(filenames):
            full = current_path / filename
            rel = f"{rel_dir}/{filename}" if rel_dir else filename
            if full.is_symlink() or _is_excluded_file(rel, filename, config):
                continue
            try:
                size = full.stat().st_size
                with full.open("rb") as handle:
                    probe = handle.read(PROBE_BYTES)
            except OSError:
                continue
            is_text = b"\x00" not in probe
            language = language_of(full)
            kind, reason = classify(rel, language, probe, is_text)
            lines = None
            if is_text and size <= MAX_LINECOUNT_BYTES:
                try:
                    data = full.read_bytes()
                    lines = data.count(b"\n") + (1 if data and not data.endswith(b"\n") else 0)
                except OSError:
                    lines = None
            inventory.files.append(FileRecord(rel, kind, language, size, is_text, lines, reason))
            if kind == "manifest":
                project_roots.add(rel_dir or ".")

    inventory.project_roots = sorted(project_roots)
    return inventory


def summarize(inventory: Inventory) -> dict[str, Any]:
    """Compact, model-friendly overview of the repository."""
    top_level = Counter()
    for f in inventory.files:
        top_level[f.path.split("/")[0] if "/" in f.path else "."] += 1
    return {
        "files": len(inventory.files),
        "by_kind": dict(sorted(inventory.by_kind().items())),
        "by_language": dict(inventory.by_language().most_common()),
        "project_roots": inventory.project_roots,
        "top_level": dict(top_level.most_common(20)),
        "excluded_dirs": len(inventory.excluded_dirs),
        "source_lines": sum(f.lines or 0 for f in inventory.files if f.kind in ("source", "test")),
    }
