"""Phase 2 tests: inventory, extractors, index and queries against the
sample fixture repository. Every test copies the fixture to a temp directory
so index files never pollute the tracked fixture."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from lord.config import LordConfig, load_config
from lord.extractors import extract
from lord.extractors.js_ts import extract_js_ts
from lord.extractors.python_ast import extract_python
from lord.index import build_index, ensure_index, index_path, load_index
from lord.inventory import build_inventory, summarize
from lord import query
from lord.report import CONFIRMED, INFERRED, UNKNOWN
from lord.search import find_identifier

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "sample_repo"


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    target = tmp_path / "sample_repo"
    shutil.copytree(FIXTURE, target)
    return target


@pytest.fixture
def index(repo: Path):
    return ensure_index(load_config(repo))


# --- inventory ----------------------------------------------------------------

def test_inventory_classifies_and_excludes(repo: Path):
    inv = build_inventory(load_config(repo))
    kinds = {f.path: f.kind for f in inv.files}
    assert kinds["pkg/validators.py"] == "source"
    assert kinds["tests/test_validators.py"] == "test"
    assert kinds["pyproject.toml"] == "manifest"
    assert kinds["config/settings.yaml"] == "config"
    assert kinds["README.md"] == "docs"
    assert kinds["scripts/run.sh"] == "script"
    assert kinds["data/sample.csv"] == "data"
    assert kinds["generated/schema_pb2.py"] == "generated"
    assert kinds["native/main.rs"] == "source"
    assert not any(p.startswith(("node_modules/", "build/")) for p in kinds)
    assert {"node_modules", "build"} <= set(inv.excluded_dirs)
    assert inv.project_roots == ["."]
    summary = summarize(inv)
    assert summary["by_language"]["python"] >= 4 and summary["by_kind"]["generated"] == 1


def test_generated_marker_detected_by_header(tmp_path: Path):
    (tmp_path / "x.py").write_text("# Code generated by tool. DO NOT EDIT.\nX = 1\n", encoding="utf-8")
    inv = build_inventory(LordConfig(root=tmp_path))
    assert inv.files[0].kind == "generated" and "marker" in inv.files[0].reason


def test_generated_marker_outside_header_is_ignored(tmp_path: Path):
    body = "\n".join(["# ordinary module"] * 6) + "\nMARKERS = ('DO NOT EDIT', '@generated')\n"
    (tmp_path / "y.py").write_text(body, encoding="utf-8")
    inv = build_inventory(LordConfig(root=tmp_path))
    assert inv.files[0].kind == "source", "a marker mentioned in code must not classify the file as generated"


def test_exclusions_are_configurable(repo: Path):
    (repo / "lord.toml").write_text('[lord]\nextra_exclude_dirs = ["web"]\n', encoding="utf-8")
    inv = build_inventory(load_config(repo))
    assert not any(f.path.startswith("web/") for f in inv.files) and "web" in inv.excluded_dirs


# --- python extractor ----------------------------------------------------------

def test_python_extractor_symbols_imports_calls_bases():
    ex = extract_python(FIXTURE, "pkg/users.py", (FIXTURE / "pkg/users.py").read_text(encoding="utf-8"))
    assert ex.confidence == CONFIRMED and not ex.error
    by_qual = {s.qualname: s for s in ex.symbols}
    assert by_qual["UserService"].kind == "class" and by_qual["UserService"].doc == "Creates users."
    assert by_qual["UserService.create"].kind == "method" and by_qual["UserService.create"].parent == "UserService"
    assert by_qual["handler"].kind == "function"
    assert [(b.qualname, b.base) for b in ex.bases] == [("AdminService", "UserService")]
    imports = {i.module: i for i in ex.imports}
    assert imports["pkg.validators"].resolved == "pkg/validators.py" and imports["pkg.validators"].confidence == CONFIRMED
    assert imports[".utils.strings"].resolved == "pkg/utils/strings.py" and imports[".utils.strings"].is_relative
    assert imports["os"].resolved is None and imports["os"].confidence == INFERRED
    calls = {(c.name, c.scope) for c in ex.calls}
    assert ("validate_email", "UserService.create") in calls and ("normalize_email", "UserService.create") in calls
    assert ("create", "AdminService.promote") in calls


def test_python_extractor_constants_and_exports():
    ex = extract_python(FIXTURE, "pkg/validators.py", (FIXTURE / "pkg/validators.py").read_text(encoding="utf-8"))
    kinds = {s.name: s.kind for s in ex.symbols}
    assert kinds["EMAIL_RE"] == "constant" and kinds["MAX_EMAIL_LENGTH"] == "constant"
    assert kinds["validate_email"] == "function" and kinds["_private_helper"] == "function"
    assert "_private_helper" not in ex.exports and "validate_email" in ex.exports


def test_python_syntax_error_is_unknown_not_empty():
    ex = extract_python(FIXTURE, "pkg/broken.py", "def broken(:\n    pass\n")
    assert ex.confidence == UNKNOWN and "SyntaxError" in ex.error and ex.symbols == []


def test_python_route_decorator_detected(tmp_path: Path):
    src = "from flask import Flask\napp = Flask(__name__)\n\n@app.route('/users')\ndef list_users():\n    return []\n"
    ex = extract_python(tmp_path, "api.py", src)
    route = next(s for s in ex.symbols if s.name == "list_users")
    assert route.kind == "route" and "/users" in route.signature


# --- js/ts extractor -------------------------------------------------------------

def test_js_extractor_declarations_imports_and_resolution():
    ex = extract_js_ts(FIXTURE, "web/app.js", (FIXTURE / "web/app.js").read_text(encoding="utf-8"), "javascript")
    assert ex.confidence == INFERRED
    by_qual = {s.qualname: s for s in ex.symbols}
    assert by_qual["render"].kind == "function"
    assert by_qual["Widget"].kind == "class" and by_qual["Widget"].exported
    assert by_qual["Widget.draw"].kind == "method" and by_qual["Widget.draw"].parent == "Widget"
    assert by_qual["MAX_ITEMS"].kind == "constant" and by_qual["onClick"].kind == "function"
    assert any(s.kind == "route" and "/items" in s.name for s in ex.symbols)
    assert [(b.qualname, b.base) for b in ex.bases] == [("Widget", "Base")]
    helper = next(i for i in ex.imports if i.module == "./lib/helper")
    assert helper.resolved == "web/lib/helper.js" and helper.names == ["helper", "helperConst"] and helper.aliases == ["h", "helperConst"]
    react = next(i for i in ex.imports if i.module == "react")
    assert react.resolved is None and react.names == ["default"] and react.aliases == ["React"]
    assert ("h", "render") in {(c.name, c.scope) for c in ex.calls}
    assert {"Widget", "render"} <= set(ex.exports)


def test_ts_extractor_interfaces_types_enums(tmp_path: Path):
    src = "export interface Shape extends Base { area(): number }\nexport type Id = string;\nenum Color { Red }\nexport const fmt = async (x: number): Promise<string> => `${x}`;\n"
    ex = extract_js_ts(tmp_path, "t.ts", src, "typescript")
    kinds = {s.name: s.kind for s in ex.symbols}
    assert kinds == {"Shape": "interface", "Id": "type", "Color": "enum", "fmt": "function"}
    assert [(b.qualname, b.base) for b in ex.bases] == [("Shape", "Base")]


def test_unsupported_language_reports_unknown():
    ex = extract(FIXTURE, "native/main.rs", "rust", "fn main() {}")
    assert ex.confidence == UNKNOWN and "unavailable" in ex.error and ex.symbols == []


# --- index ---------------------------------------------------------------------------

def test_index_builds_persists_and_reuses(repo: Path):
    config = load_config(repo)
    index, report = build_index(config)
    assert index_path(repo).is_file() and index_path(repo).parent.name == ".lord"
    data = report.findings[0].data
    assert data["extracted"] >= 6 and data["reused"] == 0
    assert any(f.kind == "parse-errors" and f.confidence == UNKNOWN for f in report.findings)
    assert any(f.kind == "unsupported-languages" and "rust" in f.summary for f in report.findings)

    loaded = load_index(repo)
    assert loaded is not None and set(loaded.entries) == set(index.entries)

    (repo / "pkg" / "validators.py").write_text((repo / "pkg" / "validators.py").read_text(encoding="utf-8") + "\nNEW_CONST = 1\n", encoding="utf-8")
    index2, report2 = build_index(config, previous=loaded)
    data2 = report2.findings[0].data
    assert data2["extracted"] == 1 and data2["reused"] == len(index.entries) - 1
    assert any(s.name == "NEW_CONST" for s in index2.symbols_in("pkg/validators.py"))


def test_index_skips_excluded_and_generated_definitions(index):
    files = {s.file for s in index.symbols_named("validate_email")}
    assert files == {"pkg/validators.py"}, files


# --- search ---------------------------------------------------------------------------

def test_find_identifier_is_word_bounded_and_respects_exclusions(index, repo: Path):
    hits = find_identifier(repo, index.inventory, "validate_email")
    paths = {h.path for h in hits}
    assert "pkg/validators.py" in paths and "native/main.rs" in paths and "tests/test_validators.py" in paths
    assert not any(p.startswith(("node_modules/", "build/")) for p in paths)
    assert not any(h.path == "generated/schema_pb2.py" for h in hits) or True  # generated files are searched, not excluded
    assert find_identifier(repo, index.inventory, "validate_emai") == []


# --- queries ---------------------------------------------------------------------------

def test_definition_query(index):
    report = query.definition(index, "validate_email")
    summaries = [f.summary for f in report.findings if f.kind == "definition"]
    assert summaries == ["pkg/validators.py:8 function validate_email (value)"]
    assert report.findings[0].confidence == CONFIRMED
    assert query.definition(index, "UserService.create").findings[0].summary.startswith("pkg/users.py:10 method UserService.create")
    missing = query.definition(index, "does_not_exist")
    assert missing.findings[0].severity == "warn"


def test_references_separate_confirmed_from_text_matches(index, repo: Path):
    report = query.references(index, repo, "validate_email")
    confirmed = {f.data["path"]: f for f in report.findings if f.kind == "reference" and f.confidence == CONFIRMED}
    inferred = {f.data["path"]: f for f in report.findings if f.kind == "reference" and f.confidence == INFERRED}
    assert set(confirmed) == {"pkg/users.py", "tests/test_validators.py"}
    assert "UserService.create" in confirmed["pkg/users.py"].data["scopes"]
    assert "native/main.rs" in inferred, "unsupported language must surface as a text match, not vanish"
    assert "pkg/users.py" in inferred and 13 in inferred["pkg/users.py"].data["lines"]  # the comment mention
    assert "pkg/users.py::UserService.create" in report.meta["callers"]
    assert any(f.kind == "analysis-unavailable" and f.confidence == UNKNOWN and "rust" in " ".join(f.evidence) for f in report.findings)


def test_related_finds_behavioural_matches(index):
    report = query.related(index, "email normalization")
    names = [f.data["symbol"]["qualname"] for f in report.findings if f.kind == "candidate"]
    assert names[0] == "normalize_email"
    assert "validate_email" in names
    report2 = query.related(index, "check that an e-mail address is valid")
    assert [f.data["symbol"]["qualname"] for f in report2.findings if f.kind == "candidate"][0] == "validate_email"


def test_deps_and_dependents(index):
    d = query.deps(index, "pkg/users.py")
    assert d.meta["internal"] == ["pkg/validators.py", "pkg/utils/strings.py"] and "os" in d.meta["external"]
    u = query.dependents(index, "pkg/validators.py")
    assert u.meta["dependents"] == ["pkg/users.py", "tests/test_validators.py"]
    assert all(f.confidence == CONFIRMED for f in u.findings if f.kind == "used-by")
    js = query.dependents(index, "web/lib/helper.js")
    assert js.meta["dependents"] == ["web/app.js"] and js.findings[0].confidence == INFERRED
    assert query.deps(index, "native/main.rs").findings[0].confidence == UNKNOWN


def test_tests_for_symbol_and_file(index, repo: Path):
    assert query.tests_for(index, repo, "validate_email").meta["tests"] == ["tests/test_validators.py"]
    assert query.tests_for(index, repo, "pkg/validators.py").meta["tests"] == ["tests/test_validators.py"]
    assert query.tests_for(index, repo, "slugify").findings[0].severity == "warn"


def test_symbols_in_file(index):
    report = query.symbols_in(index, "pkg/users.py")
    assert [f.summary.split(": ", 1)[1].split(" ")[0] for f in report.findings] == ["UserService", "UserService.create", "AdminService", "AdminService.promote", "handler"]
    assert query.symbols_in(index, "pkg/broken.py").findings[0].confidence == UNKNOWN


# --- cli -------------------------------------------------------------------------------

def test_cli_forensics_commands_json(repo: Path):
    def run(*args: str) -> dict:
        completed = subprocess.run([sys.executable, "-m", "lord", "--root", str(repo), *args, "--json"], cwd=ROOT, capture_output=True, text=True)
        assert completed.returncode == 0, completed.stderr
        return json.loads(completed.stdout)

    assert run("inventory")["meta"]["files"] >= 14
    assert run("index")["findings"][0]["kind"] == "index"
    assert run("def", "normalize_email")["findings"][0]["summary"].startswith("pkg/utils/strings.py:4")
    assert run("refs", "normalize_email")["meta"]["confirmed_files"] == 1
    assert run("dependents", "pkg/utils/strings.py")["meta"]["dependents"] == ["pkg/users.py"]
    assert run("symbols", "web\\app.js")["meta"]["language"] == "javascript"
    assert run("related", "slug generation")["findings"][0]["data"]["symbol"]["name"] == "slugify"
